name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest    
    steps:
      # - uses: actions/checkout@master
      # - uses: ./action-a
      #   env:
      #     MY_NAME: "Mona"
      - name: greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          curl -s -o /dev/null -w "%{http_code}" -X POST -F token=${{ secrets.WEBHOOK_TOKEN }} -F "ref=master" -F "variables[IMAGE_TAG]=latest"  ${{ secrets.WEBHOOK_URL }}